version: "3"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_IP=host.docker.internal
      - TF_CPP_MIN_LOG_LEVEL=3
      - TRAIN_DATA_PATH=/app/data/fashion_mnist/train
      - LOG_PATH=/app/logs/clients
    volumes:
      - /Users/ayushtiwari/Desktop/federated-learning/logs:/app/logs
      - /Users/ayushtiwari/Desktop/federated-learning/data:/app/data
    tty: true
    command: ["python", "client.py"]
